version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: team_management
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/init_db.sql # Adiciona o script SQL aqui


  web:
    build: .
    command: >
      sh -c "
        until mysqladmin ping -h db --silent; do
          echo 'Waiting for database...';
          sleep 2;
        done;
        python ./teamManagement/manage.py migrate &&
        python ./teamManagement/manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=team_management
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3306

volumes:
  db_data:
