# Generated by Django 5.1.2 on 2024-11-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('premiacao', models.CharField(max_length=100)),
                ('dt_inicio', models.DateField()),
                ('dt_termino', models.DateField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
