# Generated by Django 5.1.2 on 2024-11-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('posicao', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('tempo_contrato', models.CharField(max_length=100)),
                ('titular', models.BooleanField()),
                ('dt_nascimento', models.DateField()),
                ('salario', models.FloatField()),
            ],
        ),
    ]
