# Generated by Django 5.1.2 on 2024-11-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jogador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('dt_fundacao', models.DateField()),
                ('titulos', models.CharField(max_length=255)),
            ],
        ),
    ]
